spring:
  application:
    name: crud_app
sql:
  sqlFindAll: "SELECT * FROM userTable"
  sqlSave: "INSERT INTO userTable (firstName, lastName) VALUES (?, ?)"
  sqlDeleteById: "DELETE FROM userTable WHERE id=?"
  sqlUpdateUser: "UPDATE userTable SET firstName = ?, lastName = ? WHERE id = ?"
  sqlGetUser: "SELECT * FROM userTable WHERE id = "